// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/aside/Aside.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HotCard: typeof import('./src/components/hot-card/HotCard.vue')['default']
    Logo: typeof import('./src/components/header/components/Logo.vue')['default']
    Nav: typeof import('./src/components/header/components/Nav.vue')['default']
    Page: typeof import('./src/components/page/Page.vue')['default']
    PageAside: typeof import('./src/components/page-aside/PageAside.vue')['default']
    PageHeader: typeof import('./src/components/page-header/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/header/components/User.vue')['default']
  }
}
